### ISSUE TITLE
There is no straight download link to Origins Classes mod.

### ISSUE THREAD

**Issue by maxmanchik** [apace100/origins-classes#18]
I can't find Origins Classes on CurseForge even if I search for it. In CurseForge is literally no such mod.

**Comment by timelady-victorious** [comment]
https://www.curseforge.com/minecraft/mc-mods/origins-classes

**Comment by timelady-victorious** [comment]
Close this please?

**Comment by maxmanchik** [comment]
ok

**Comment by maxmanchik** [comment]
> Close this please?

thanks, and ok
