### ISSUE TITLE
[Suggestion] Allow a user to define custom classes

### ISSUE THREAD

**Issue by Sunconure11** [apace100/origins-classes#25]
Unless this is already in and I’m an idiot, there is no indication that one can make their own classes via this mod. Would it be feasible to implement such?

**Comment by Sunconure11** [comment]
Okay, it appears I’m just an idiot. Could you make this more clear, in the CF page?

**Comment by apace100** [comment]
Yeah, this is possible, sorry if it wasn't stated anywhere! I'll add a line to the CF page, thanks for suggesting that.
