### ISSUE TITLE
Beastmaster cannot tame Parrots

### ISSUE THREAD

**Issue by LocoPineapples** [apace100/origins-classes#32]
It's as the title says, Beastmasters are unable to tame any parrots. Any other animal can be tamed normally, and foxes and ocelots can still be trusted, but parrots simply won't tame, no matter how many seeds are given. Other classes can still tame them, though.

**Comment by quickquail** [comment]
just confirming this issue. beast master, no parrots :(

**Comment by apace100** [comment]
Fixed in 1.2.0
