### ISSUE TITLE
Wander Trader Doesn't get Affected By Merchant

### ISSUE THREAD

**Issue by Randomspy1** [apace100/origins-classes#34]

**Comment by YoJames2019** [comment]
can confirm

**Comment by apace100** [comment]
What do you mean exactly? You mean the additional trades don't show up?

If you are talking about the trades exhausting and being unavailable after having traded X times - that is intentional. Only the regular villagers will trade with merchants indefinitely.

**Comment by Randomspy1** [comment]
oh i thought it was a bug i guess not
