### ISSUE TITLE
Doggies cant get the Beastmaster's healthboost

### ISSUE THREAD

**Issue by sXKYYYY** [apace100/origins-classes#36]
![2021-05-26_03 51 07](https://user-images.githubusercontent.com/84809193/119559789-b3f82580-bdd5-11eb-8b14-aedb748ba32e.png)
![2021-05-26_03 51 25](https://user-images.githubusercontent.com/84809193/119559809-bc506080-bdd5-11eb-82f8-f67c50f26c26.png)

**Comment by apace100** [comment]
Fixed in 1.2.0
