### ISSUE TITLE
Item Dublication: Explorer get items every time I relog into a server

### ISSUE THREAD

**Issue by darkrider0** [apace100/origins-classes#40]
I'm playing the Explorer class and every time I log in to my server I get a copy of all 9 maps, compass, and clock.

I will look for a log and post it

Edit:
Found this. Appears in the server console when I log in. Seems related:
[19:12:11] [Server thread/WARN]: Player class_3222['Ninjaneer0'/27463, l='ServerLevel[world]', x=8.03, y=64.00, z=671.11] could not be synced because server networking isn't set up yet.

Edit 2: Latest log file:
[latest.log](https://github.com/apace100/origins-classes/files/6689038/latest.log)

**Comment by apace100** [comment]
Should be fixed if you update your Origins version (not Origins: Classes, though you can update that too). Let me know if you're still experiencing this, then I'll reopen this issue.
