### ISSUE TITLE
Cleric Crashes the Game

### ISSUE THREAD

**Issue by ChromexUnderscore** [apace100/origins-classes#46]
I was extending my strength II throwable potions, it suddently crashed Minecraft.
I think its because the extending needs more water than my Cauldron contained
I forgot to copy the Error Code :/
But Heres my Crash Report
[crash-2021-07-10_16.56.22-client.txt](https://github.com/apace100/origins-classes/files/6795471/crash-2021-07-10_16.56.22-client.txt)

Edit 07/12/2021
I just found that if you try to fill a cauldron, it somehow crashed my game.
Crash report :
[crash-2021-07-12_20.47.02-client.txt](https://github.com/apace100/origins-classes/files/6803720/crash-2021-07-12_20.47.02-client.txt)

**Comment by apace100** [comment]
Fixed in 1.2.2
