### ISSUE TITLE
Custom classes create a new "layer"

### ISSUE THREAD

**Issue by UomoSaiber** [apace100/origins-classes#50]
Hi, I was trying to implement a new class through a datapack, the problem is that instead of the new class apearing inside the class list it appears as another menu saying "choose your layer.nomad.class.name" (nomad being the name of the class I am trying to implement) with only that class, is there something I am not getting?, I haven't been able to find anyone who as tried makeing a custom class and has posted something on the internet and I feel like I have tried everything.

**Comment by c0rvoid** [comment]
Make sure the name of the folder is `origins-classes` and not `origins_classes` (or similar.)

**Comment by apace100** [comment]
Yeah, there's definitely something wrong on your end. Here's an example custom class datapack:
[Pirate.zip](https://github.com/apace100/origins-classes/files/8495274/Pirate.zip)
