### ISSUE TITLE
Just a quick question - what is are the things that a wandering trader can trade with a merchant

### ISSUE THREAD

**Issue by KateIsEpic** [apace100/origins-classes#58]
Im just curious if there are things that are off limits or is it anything?

**Comment by RaymondBlaze** [comment]
Merchant will have 2 extra offer from Wandering Traders:
1. 6-17 emerald for 1 random item (enchanted with level 1-30 if enchantable)
2. 1-16 random item for 1 random item  (enchanted with level 1-30 if enchantable)

The random item here is all the items you can get from all the loot tables, except for those in tag `origins-classes:merchant_blacklist`. You may see the default value of the tag [here](https://github.com/apace100/origins-classes/blob/1.18/src/main/resources/data/origins-classes/tags/items/merchant_blacklist.json).
