### ISSUE TITLE
Upload to moderinth 

### ISSUE THREAD

**Issue by PolyframeX** [apace100/origins-classes#72]
It would be very nice if you were to be able to upload this mod to moderinth, its simple, easy, and will make your mod more accessible to others.

**Comment by WimpieRatte** [comment]
Heh? But it's already on Modrinth?

**Comment by PolyframeX** [comment]
Oh my bad, I see the issue now, Origins: Classes didn't show up because it's not on 1.19.2 on Modrinth, its only on 1.19 and 1.19.1.
